### ISSUE TITLE
Live transcription

### ISSUE THREAD

**Issue by SaranjeetKaur** [RSEAA/RSEAA.github.io#12]
Shared some options for live transcriptions with Rowland along with some numbers on expected costs

**Comment by rowlandm** [comment]
From Saranjeet

Hello Rowland and Andrea,


Just sharing a brief context - I had sent a message to Heather Turner asking for suggestions and experiences around live transcriptions as she was involved with the useR! 2021 (online conference) organisation. 


She suggested that I should talk to Andrea (who is right now here in-person at the Collab Workshop) as Andrea did a lot of investigation into this for 2021.


Summarising some of Andrea's suggestions:

- Find the vendors for live transcriptions earlier rather than later, if possible. 

- Some vendors provide demonstrations during the negotiation stage.


Summarising some of Heather's suggestions:

- White Coat Captioning - For remote captioning of useR! 2022 Keynotes (6): $2,115.00

useR! 2021 Keynote Captioning (Live Captions English + Spanish, ai media, 8 keynotes): $15.225,00

- Spanish was a lot more expensive? Quotes do seem to vary quite a bit.

- Otter AI doesn't seem too bad at CW23 - could be good for the non-keynotes. 

- Another service that to try is "scribe captioning" (https://www.ava.me/scribe) - the idea is that it is better than AI captioning and more affordable than live captioning.


Andrea - please add anything that I missed here. Also if possible, could you please share some links or vendor information with us?

**Comment by SaranjeetKaur** [comment]
Potentially ask the speakers to provide accessible slides

**Comment by SaranjeetKaur** [comment]
If we don't need a accessibility partner who would pay for it then we might go with the default Zoom captioning

**Comment by shyamaW** [comment]
@SaranjeetKaur Gentle Reminder!

Any updates about this task?

**Comment by rowlandm** [comment]
I agree Saranjeet, if we can't find anyone we have to go with default Zoom captioning.

Are there at least some quotes we can find out?

**Comment by shyamaW** [comment]
Hi @SaranjeetKaur @rowlandm 

How about the live transcription?
are we going with the default Zoom Captioning? Has this been finalized/done?

**Comment by rowlandm** [comment]
Default is going with Zoom live. If we get time we can chase this up.

For me this is a nice to have - I will be putting my efforts into the speakers delivering accessible presentations.

**Comment by SaranjeetKaur** [comment]
Looking at the pricing of hybrid AI scribes: https://www.ava.me/pricing. It seems they offer a non-profit discount on their prices.

**Comment by rowlandm** [comment]
From White Coat Captioning - recommended from people in the US Python conference community.

About $2000 AUD for the two keynotes and senior panel

[Estimate RSE23.pdf](https://github.com/RSEAA/RSEAA.github.io/files/12265090/Estimate.RSE23.pdf)

**Comment by rowlandm** [comment]
The senior panel would need to be 1 hour instead of 1.5 hours to be aligned with this quote.

**Comment by rowlandm** [comment]
Also tried to ask for a quote from https://www.redbeemedia.com/quote/

**Comment by rowlandm** [comment]
Hello Rowland!

Thanks for checking in.   It will be ok if the time changes to a 1:30 UTC +10 start, but we would need to know with plenty of time.

I just sent you a 2nd estimate in the event you decide instead to have captioning 1:00-5:00pm UTC +10     (or 1:30-5:30 as above)

Please do note this is special pricing available until August 11.   Pricing will increase after that time.

We look forward to working with you.   Let me know if you have any additional questions.

Brenda

[Estimate RSElong.pdf](https://github.com/RSEAA/RSEAA.github.io/files/12265357/Estimate.RSElong.pdf)

**Comment by rowlandm** [comment]
Red Bee Media - 

 

To give you an idea of costs (all prices exclude GST), the first hour of any event is $270, and then each subsequent hour is $220 per hour, charged in 15-min increments.

We can insert captions directly into Zoom for your event.

If there were any breakout rooms, we would provide a URL that the captions could be displayed on for each room and accessed by any attendees in that room. Captioning in breakout rooms can be temperamental in Zoom, so this is the most reliable solution.

Would you require any post-event subtitling file for any on-demand services?

Please note any cancellations within 24 hours are charged in full.

 

What time each day do you require captions for?

Would any material be available? This could be scripts or media files.

Are captions to be inserted into Zoom itself?

We can also provide a URL that captions will appear on.

Captioners would join the Zoom event itself to receive audio and video.

 

Based on the below, the cost would be $810 for the three sessions over the three days.

**Comment by rowlandm** [comment]
Red Bee - $810 AUD
White Coat ~ $1800 AUD ($1200 USD)

**Comment by rowlandm** [comment]
Saranjeet and Rowland agreed to try Red Bee this year.

**Comment by rowlandm** [comment]
Had to ask Mark Crowe to fill out a Sarbane Oxley form for Red Bee Media.

**Comment by rowlandm** [comment]
And I will pass on the instructions for Zoom here, too.
We require an API token to link up your Zoom webinar to our software. Details below.
To enable captions on Zoom, you must enable some settings in the Zoom account that will be used for the event.
Please send Zoom invites for the event itself to the Service Delivery inbox, cced here. I am in the Uk so they monitor everything on the day.
We need to receive the API token no later than 30 minutes before the start of your event to link up your meeting to our captioning software.

Ahead of the event, log into the Zoom account online – rather than opening the Zoom app itself – and go to Settings, and set the account as below. Very important that Automated Captions are turned off as they can interfere with our captions.



When you start the Zoom event using this account, at the bottom of the screen in Zoom you will find a CC Show Captions button. Click the up arrow on this button > Set up manual captioner > Copy API token.
Email this token to EBMS AU Service Delivery [service.delivery.ebms.au@redbeemedia.com](mailto:service.delivery.ebms.au@redbeemedia.com), please, and they will hook up your meeting to our software.
Please also ensure your Zoom account is not geo-locked – ie it will allow attendees from anywhere in the world.
