### ISSUE TITLE
Check passwords are shared

### ISSUE THREAD

**Issue by rowlandm** [RSEAA/RSEAA.github.io#73]

**Comment by rowlandm** [comment]
use rse2024@rse-aunz.org as email if you can.

Need to share for:

- Twitter (to be created)
- LinkedIn
- Mastadon
- Registration eg. Eventbrite?
- Zoom One Plus (use events@rse-aunz.org)

**Comment by rowlandm** [comment]
And make sure access is OK for:
- Google Drive
- GitHub Projects
- GitHub website

**Comment by rowlandm** [comment]
Gave Chris and Richard access to RSEAA github website.

**Comment by rowlandm** [comment]
Gave Richard and Chris admin rights for https://www.linkedin.com/company/97922853/admin/feed/posts/

**Comment by rowlandm** [comment]
Send username and password to Chris and Richard for Mastadon.
rowland.h.mosbergen@gmail.com and the server is https://social.foss.place/auth/sign_up

**Comment by rowlandm** [comment]
So that only leaves us:
1. Google Drive access
2. Registration for paying members (we have to work that out later)
3. Zoom One Plus (we can do that later)

**Comment by richarddushime** [comment]
Twitter Creation 
Details 
@rowlandm i would like to confirm the email to use while creating the twitter account 
i wanted to use **rse2024@rse-aunz.org** but  looks  not good to me , since this email will always be changed  every year , or for twitter account it will remain there more years 
my suggestion is 
Do you have an alternative email ?
if not would you create a standard one ?like  **rse@rse-aunz.org** that we can be using

If confirm the above i will go ahead 
Thank you

**Comment by rowlandm** [comment]
Good point.

We might keep rse2024 for now.
Next year we can use something else, like rseaa@rse-aunz.org.

For this year let's use rse2024.

**Comment by richarddushime** [comment]
We now have a twitter Account 
Here is the link  : [Twitter](https://twitter.com/RSE_asia_austra) 
i will share other details privately

**Comment by rowlandm** [comment]
Nice!

**Comment by richarddushime** [comment]
Ready shared the details and Added  to the [document Registry ](https://docs.google.com/spreadsheets/d/1qAPJL13eOCeGBLn87PQj5zIkGE6yDzLr4dJFhgbu3cc/edit?usp=sharing)

**Comment by rowlandm** [comment]
Richard and Rowland can access posting for:

1. LinkedIn
2. Twitter
3. Mastadon

Can close this.
