### ISSUE TITLE
Finalise Programme schedule and look into lightning talks and poster session

### ISSUE THREAD

**Issue by shyamaW** [RSEAA/RSEAA.github.io#8]

**Comment by rowlandm** [comment]
https://docs.google.com/spreadsheets/d/1s7vYI4bPSkM6Q85YHZdefuv2z0EE1OxvXfI-dxns1bM/edit#gid=0 

Did we decide how we might do the format for the lightning talks and poster session @GraceAHall?

I was thinking of an idea - like have everyone put in a digital poster and then on the day we could see votes for people to give their lightning talk of the poster. Did we discuss something like this in the meeting?

**Comment by rowlandm** [comment]
Some alternatives to Fourwaves are:

- **Cvent**: a platform that provides easy-to-use, integrated technology solutions to maximize the impact of meetings and events of all sizes².
- **vFairs**: a platform that helps event organizers make memorable connections with their target audience by providing virtual booths, webinars, chat rooms, networking lounges, and more².
- **Whova**: a platform that simplifies event management and enhances attendee engagement with features such as agenda, speaker bios, live polls, surveys, networking, and gamification².
- **ON24**: a platform that offers a portfolio of webinar, virtual event and content experiences that drive engagement, generate first-party data, and deliver revenue growth².
- **Livestorm**: a platform that enables webinars and live meetings from the browser, with chat and questions, analytics, integrations, and more².
- **Hopin**: a platform that allows attendees to learn, interact, and connect with people from anywhere in the world through stages, networking, breakout sessions, sponsors, tickets, and more².
- **Airmeet**: a platform that hosts interactive virtual events such as conferences, summits, meetups, workshops, and more with features such as social lounge, speed networking, backstage, polls, Q&A, and more².
- **Hubilo**: a platform that transforms events into engaging and interactive experiences with features such as virtual booths, live streaming, breakout rooms, gamification, networking tables, and more².

You can compare these alternatives based on user reviews, pricing information, and features on websites such as G2², TrustRadius³, or Capterra⁴.

Origen: Conversación con Bing, 3/6/2023
(1) Top 10 Fourwaves Alternatives 2023 | G2. https://www.g2.com/products/fourwaves/competitors/alternatives.
(2) List of Best Fourwaves Alternatives & Competitors 2022 - TrustRadius. https://www.trustradius.com/products/fourwaves/competitors.
(3) Best Fourwaves Alternatives 2023 | Capterra. https://www.capterra.com/p/237345/Fourwaves/alternatives/.
(4) Top 10 Fourwaves Alternatives 2023 | G2. https://bing.com/search?q=alternatives+to+fourwaves.

**Comment by rowlandm** [comment]
I like this interface - and the fact you can vote for a poster...

https://demo.virtualpostersession.org/#track1.%20Keynote

**Comment by rowlandm** [comment]
Another option - [Acadiate](https://www.acadiate.com/)

This is an [example of their poster session](https://www.acadiate.com//ee/acadiate/Poster_Lobby)

It must be hosted overseas as it seems quite slow.

**Comment by rowlandm** [comment]
[Whova](https://www.youtube.com/watch?v=13PWmLApS1M) is also another option - but I think it is pricier.

**Comment by rowlandm** [comment]
Agreement to:

1. Have people be able to upload a poster.
2. Have the community vote for their favourites (all the posters) with no limit to the numnber of votes.
3. The top X posters could be invited for a lightniting talk at the end of the poster session.
4. People could highlight if they do not want to give a lightning talk when they upload the poster.
5. We start from the most popular and work our way down to see who would want to give a lightning talk.
6. Need to check that the poster is appropriate.
7. Would have dedicated time in the conference to get people to look at posters and possibly interact with the poster person. At the end of the dedicated time we could then tally up the votes and perhaps even go straight into the lightning talk.


We need to find a system that can do this by some arbitrary date otherwise we can leave this idea for 2024.

It would be nice to have a formal example and an informal example of posters.

**Comment by rowlandm** [comment]
It was also mentioned that we could have a poster session on the start of the 2nd day. There could be a possible award or awards (like a digital certificate) to show that they were one of the most popular community posters for RSEAA2023.
